#!/usr/bin/env bash
# displays Best School 10 thimes but at the 9th iteration displays Best school then  Hi on new line

count=0

while [ $count -lt 10 ]
do
    if [ $count -eq 9 ]
    then
	echo "Hi"
    fi
        echo "Best School"
        ((count ++))
done
