#!/usr/bin/env bash
# displays 4 and then bad luck from china
# displays 9 and then bad luck from japan
# displays 17 and bad luck from italy
# displays numbers 1 -20

count=1
while [ $count -le 20 ]
do
    echo "$count"
    case $count in
	"4") echo "bad luck from China"
	"9") echo "bad luck from Japan"
	"17")echo "bad luck from Italy"
     esac
     (( count++ ))
done	     
