#!/usr/bin/env bash
# displays content of current directory
# content in a list format
# content where only the part of the name is displayed

list=$(ls)
for i in $ list; do
    echo  "$i" | cut -d '-' -f2
done
